include_recipe "pivotal_workstation::create_var_chef_cache"
include_recipe "sprout-osx-apps::skype"
include_recipe "sprout-osx-apps::firefox"
include_recipe "pivotal_workstation::inputrc"
include_recipe "sprout-osx-apps::chrome"
include_recipe "sprout-osx-settings::defaults_fast_key_repeat_rate"
include_recipe "pivotal_workstation::bettertouchtool"
